### ISSUE TITLE
Add to VGPS issue

### ISSUE THREAD

**Issue by BBosman** [ganja1447/greasemonkey-geocaching-projectgc#26]
If you open a couple of caches in (quick) succession, they will all add the last cachepage loaded to VGPS.

This is due to the fact that GM_setValue (during load) and GM_getValue (during add) are used to store and retrieve the GC code, making it a last write wins issue.

**Comment by ganja1447** [comment]
Yes, here is definitely a race condition. We can easily solve that by using the already existing function to get the gccode instead. Which if I remember correctly is just one line of jQuery.

In general we should look into eliminating as many save/get we can. I assume we don't really  need a single one of them.

**Comment by ganja1447** [comment]
I believe this is fixed in the develop branch now. I haven't really tested it, but I removed the GM_setValue and GM_getValue for everything except settings.

This should be a more correct behaviour. The only downside is that no  API calls will be made until CheckPGCLogin's api call has been returned. Since this is a major code change, next version will be 1.5.0 (when released). However there is nothing visible to the end users.
